In [104]:
!pip install boto3
import matplotlib.pyplot as plt
import pandas as pd
import numpy as np
import boto3
from sklearn.model_selection import train_test_split
from io import BytesIO

In [114]:
my_aws_access_key_id='ASIAYAAO5HRMMO7ULB2W'
my_aws_secret_access_key='pyqATpD3j583ftf0LFAzS9otb7yYVRexBm7leHI3'
my_aws_session_token='IQoJb3JpZ2luX2VjEJr//////////wEaCXVzLWVhc3QtMiJHMEUCIQCTCbUgA1UfHCGYqDcLmk80Au0cDSmSWlF79utIVunAHwIgZiwrAH0lOkrz+untY/xCAKjIXapDxd41xBkIiukDOJYq9AIIs///////////ARAAGgw1NDk3ODcwOTAwMDgiDMTlz+Szpu3f7gbU3SrIAts4c7luZShTv8o963Q77W593n+a3Wq6jPI/wklis1es8pWAt1adpfoK7i02jx3IJfCfp4yjBAj3XLY5hoWdrfjEwRmAPFpQfNJpZCf0ESMaaqslGCCmXjqadbn2nL8e9mhG3+TLwMFTwRS2NZrNnImHOHDWrYjkKSsVZkNKVRhOoNqonB2PVmR1mgrv5ffd0a0rl2iC5i54FrIO0HwkFr/0jS6Fx8qapQqvI2/FwyPzlI1kjn4hocYjX/QD4Q0deSLPfz2abLCz5VB3fIQHuWtiT82VAN/kks+QAKTBdDV31FOUd0vwg00bD3MLsvD9rZIt27L+19WdPwZ04uH9mx2Kjd9GyRWxHEytFy3QcUibVlH1YVgMW5W4EQrH8SyM2E/dQE2Zws5KIgY6kXghMguSDv6QBrxq4TCEl7s+5sDqEfDKaTFYrcYwjsKlvQY6pwESP58bGAzCgMyUKM30clzPRnx8jVrtwDC/Qghw8ZBxR7xFFOaH6XWRy9jY2YJ2SOTgsqOhhjyes0zELdkL2THc8YKJWR7jUcbpBOUlsC99PbBWfKdXFjuexTYobkC3YQY8Cnb78bUe6xKdQNfiT8SCuQnV6g0OU61kfIgs4Kpsv1GJyw2xpVWZ2461uo0+jfw+btHnI9WMyBJd8qw93k4k/SXPOTvUAQ=='

use_cols = ["age", "sex", "painloc", "painexer", "cp", "trestbps", "smoke", "fbs", "prop", "nitr", "pro", "diuretic", "thaldur", "thalach", "exang", "oldpeak", "slope", "target"]

s3 = boto3.client('s3',
                  aws_access_key_id=my_aws_access_key_id,
                  aws_secret_access_key=my_aws_secret_access_key,
                  aws_session_token=my_aws_session_token)


bucket_name = 'de300winter2025'
object_key = 'aidan_mott/heart_disease.csv'
csv_obj = s3.get_object(Bucket=bucket_name, Key=object_key)
body = csv_obj['Body']
csv_string = body.read().decode('utf-8')
df = pd.read_csv(BytesIO(csv_string.encode()), usecols=use_cols)
df = df.head(899) # data after here was corrupted
df

age  sex  painloc  painexer   cp  trestbps  smoke  fbs  prop  nitr  pro  \
0    63  1.0      NaN       NaN  1.0     145.0    NaN  1.0   0.0   0.0  0.0   
1    67  1.0      NaN       NaN  4.0     160.0    NaN  0.0   1.0   0.0  0.0   
2    67  1.0      NaN       NaN  4.0     120.0    NaN  0.0   1.0   0.0  0.0   
3    37  1.0      NaN       NaN  3.0     130.0    NaN  0.0   1.0   0.0  0.0   
4    41  0.0      NaN       NaN  2.0     130.0    NaN  0.0   0.0   0.0  0.0   
..   ..  ...      ...       ...  ...       ...    ...  ...   ...   ...  ...   
894  54  1.0      1.0       1.0  4.0     180.0    NaN  NaN   0.0   0.0  0.0   
895  56  1.0      1.0       1.0  4.0     125.0    1.0  1.0   0.0   0.0  0.0   
896  56  1.0      0.0       1.0  3.0     125.0    NaN  NaN   0.0   0.0  0.0   
897  54  1.0      1.0       1.0  4.0     130.0    NaN  NaN   0.0   0.0  0.0   
898  66  0.0      1.0       1.0  4.0     155.0    NaN  NaN   0.0   0.0  0.0   

     diuretic  thaldur  thalach  exang  oldpeak  slope  target  
0         0.0     10.5    150.0    0.0      2.3    3.0     0.0  
1         0.0      9.5    108.0    1.0      1.5    2.0     1.0  
2         0.0      8.5    129.0    1.0      2.6    2.0     1.0  
3         0.0     13.0    187.0    0.0      3.5    3.0     0.0  
4         0.0      7.0    172.0    0.0      1.4    1.0     0.0  
..        ...      ...      ...    ...      ...    ...     ...  
894       0.0      7.5    150.0    0.0      1.5    2.0     1.0  
895       0.0      6.5    103.0    1.0      1.0    2.0     1.0  
896       0.0      6.0     98.0    0.0     -2.0    2.0     1.0  
897       0.0      9.5    110.0    1.0      3.0    2.0     1.0  
898       0.0      6.5     90.0    0.0      0.0    NaN     1.0  

[899 rows x 18 columns]

In [115]:
plmode = df['painloc'].mode()[0]
df['painloc'] = df['painloc'].fillna(plmode)
pemode = df['painexer'].mode()[0]
df['painexer'] = df['painexer'].fillna(pemode)

df.loc[df['trestbps'] < 100, 'trestbps'] = 100
trestbps_mean = df.loc[:, 'trestbps'].mean()
df['trestbps'] = df['trestbps'].fillna(trestbps_mean)

df.loc[df['oldpeak'] < 0, 'oldpeak'] = 0
df.loc[df['oldpeak'] > 4, 'oldpeak'] = 4
oldpeak_mean = df.loc[:, 'oldpeak'].mean()
df['oldpeak'] = df['oldpeak'].fillna(oldpeak_mean)

thaldur_mean = df.loc[:, 'thaldur'].mean()
thalach_mean = df.loc[:, 'thalach'].mean()
df['thaldur'] = df['thaldur'].fillna(thaldur_mean)
df['thalach'] = df['thalach'].fillna(thalach_mean)

ilist = ['fbs', 'prop', 'nitr', 'pro', 'diuretic', 'exang']
for i in ilist:
    df.loc[df[i] > 1, i] = 1
    mode = df[i].mode()[0]
    df[i] = df[i].fillna(mode)

slope_mean = df.loc[:, 'slope'].mean()
df['slope'] = df['slope'].fillna(slope_mean)
df

age  sex  painloc  painexer   cp  trestbps  smoke  fbs  prop  nitr  pro  \
0    63  1.0      1.0       1.0  1.0     145.0    NaN  1.0   0.0   0.0  0.0   
1    67  1.0      1.0       1.0  4.0     160.0    NaN  0.0   1.0   0.0  0.0   
2    67  1.0      1.0       1.0  4.0     120.0    NaN  0.0   1.0   0.0  0.0   
3    37  1.0      1.0       1.0  3.0     130.0    NaN  0.0   1.0   0.0  0.0   
4    41  0.0      1.0       1.0  2.0     130.0    NaN  0.0   0.0   0.0  0.0   
..   ..  ...      ...       ...  ...       ...    ...  ...   ...   ...  ...   
894  54  1.0      1.0       1.0  4.0     180.0    NaN  0.0   0.0   0.0  0.0   
895  56  1.0      1.0       1.0  4.0     125.0    1.0  1.0   0.0   0.0  0.0   
896  56  1.0      0.0       1.0  3.0     125.0    NaN  0.0   0.0   0.0  0.0   
897  54  1.0      1.0       1.0  4.0     130.0    NaN  0.0   0.0   0.0  0.0   
898  66  0.0      1.0       1.0  4.0     155.0    NaN  0.0   0.0   0.0  0.0   

     diuretic  thaldur  thalach  exang  oldpeak     slope  target  
0         0.0     10.5    150.0    0.0      2.3  3.000000     0.0  
1         0.0      9.5    108.0    1.0      1.5  2.000000     1.0  
2         0.0      8.5    129.0    1.0      2.6  2.000000     1.0  
3         0.0     13.0    187.0    0.0      3.5  3.000000     0.0  
4         0.0      7.0    172.0    0.0      1.4  1.000000     0.0  
..        ...      ...      ...    ...      ...       ...     ...  
894       0.0      7.5    150.0    0.0      1.5  2.000000     1.0  
895       0.0      6.5    103.0    1.0      1.0  2.000000     1.0  
896       0.0      6.0     98.0    0.0      0.0  2.000000     1.0  
897       0.0      9.5    110.0    1.0      3.0  2.000000     1.0  
898       0.0      6.5     90.0    0.0      0.0  1.766497     1.0  

[899 rows x 18 columns]

In [116]:
import requests
from bs4 import BeautifulSoup
req = requests.get('https://www.abs.gov.au/statistics/health/health-conditions-and-risks/smoking-and-vaping/latest-release')
soup = BeautifulSoup(req.content, 'html.parser')
content = soup.find_all('div', class_='chart-table-group')
next = content[2].find_all('div', class_='abs-file-field-chart-wrapper panel-wrapper table-wrapper no-footer') # this gets the right table
bodies = next[0].find('tbody')
df['age'] = pd.to_numeric(df['age'])
df['smoke_1'] = df['smoke'].copy()
for r in bodies.find_all('tr'):
  range = r.find('th').text.split('–')
  #print(range)
  value = float(r.find_all('td')[9].text) # 9 has the data from 2022
  #print(value)
  if len(range) != 1:
    low_bound = int(range[0])
    high_bound = int(range[1])
    df.loc[(np.isnan(df['smoke_1'])) & (df['age'] >= low_bound) & (df['age'] <= high_bound), 'smoke_1'] = value / 100.0
  else:
    df.loc[(np.isnan(df['smoke_1'])) & (df['age'] >= 75), 'smoke_1'] = value / 100.0
df['smoke_1']

0      0.149
1      0.087
2      0.087
3      0.109
4      0.109
       ...  
894    0.138
895    1.000
896    0.149
897    0.138
898    0.087
Name: smoke_1, Length: 899, dtype: float64

In [117]:
df['smoke_2'] = df['smoke'].copy()
df['sex'] = pd.to_numeric(df['sex'])

df.loc[(np.isnan(df['smoke_2'])) & (df['age'] >= 18) & (df['age'] <= 24) & (df['sex'] == 0), 'smoke_2'] = 0.048
df.loc[(np.isnan(df['smoke_2'])) & (df['age'] >= 18) & (df['age'] <= 24) & (df['sex'] == 1), 'smoke_2'] = 0.048 * 1.32

df.loc[(np.isnan(df['smoke_2'])) & (df['age'] >= 25) & (df['age'] <= 44) & (df['sex'] == 0), 'smoke_2'] = 0.125
df.loc[(np.isnan(df['smoke_2'])) & (df['age'] >= 25) & (df['age'] <= 44) & (df['sex'] == 1), 'smoke_2'] = 0.125 * 1.32

df.loc[(np.isnan(df['smoke_2'])) & (df['age'] >= 45) & (df['age'] <= 64) & (df['sex'] == 0), 'smoke_2'] = 0.151
df.loc[(np.isnan(df['smoke_2'])) & (df['age'] >= 45) & (df['age'] <= 64) & (df['sex'] == 1), 'smoke_2'] = 0.151 * 1.32

df.loc[(np.isnan(df['smoke_2'])) & (df['age'] >= 65) & (df['sex'] == 0), 'smoke_2'] = 0.087
df.loc[(np.isnan(df['smoke_2'])) & (df['age'] >= 65) & (df['sex'] == 1), 'smoke_2'] = 0.087 * 1.32
df

age  sex  painloc  painexer   cp  trestbps  smoke  fbs  prop  nitr  pro  \
0     63  1.0      1.0       1.0  1.0     145.0    NaN  1.0   0.0   0.0  0.0   
1     67  1.0      1.0       1.0  4.0     160.0    NaN  0.0   1.0   0.0  0.0   
2     67  1.0      1.0       1.0  4.0     120.0    NaN  0.0   1.0   0.0  0.0   
3     37  1.0      1.0       1.0  3.0     130.0    NaN  0.0   1.0   0.0  0.0   
4     41  0.0      1.0       1.0  2.0     130.0    NaN  0.0   0.0   0.0  0.0   
..   ...  ...      ...       ...  ...       ...    ...  ...   ...   ...  ...   
894   54  1.0      1.0       1.0  4.0     180.0    NaN  0.0   0.0   0.0  0.0   
895   56  1.0      1.0       1.0  4.0     125.0    1.0  1.0   0.0   0.0  0.0   
896   56  1.0      0.0       1.0  3.0     125.0    NaN  0.0   0.0   0.0  0.0   
897   54  1.0      1.0       1.0  4.0     130.0    NaN  0.0   0.0   0.0  0.0   
898   66  0.0      1.0       1.0  4.0     155.0    NaN  0.0   0.0   0.0  0.0   

     diuretic  thaldur  thalach  exang  oldpeak     slope  target  smoke_1  \
0         0.0     10.5    150.0    0.0      2.3  3.000000     0.0    0.149   
1         0.0      9.5    108.0    1.0      1.5  2.000000     1.0    0.087   
2         0.0      8.5    129.0    1.0      2.6  2.000000     1.0    0.087   
3         0.0     13.0    187.0    0.0      3.5  3.000000     0.0    0.109   
4         0.0      7.0    172.0    0.0      1.4  1.000000     0.0    0.109   
..        ...      ...      ...    ...      ...       ...     ...      ...   
894       0.0      7.5    150.0    0.0      1.5  2.000000     1.0    0.138   
895       0.0      6.5    103.0    1.0      1.0  2.000000     1.0    1.000   
896       0.0      6.0     98.0    0.0      0.0  2.000000     1.0    0.149   
897       0.0      9.5    110.0    1.0      3.0  2.000000     1.0    0.138   
898       0.0      6.5     90.0    0.0      0.0  1.766497     1.0    0.087   

     smoke_2  
0    0.19932  
1    0.11484  
2    0.11484  
3    0.16500  
4    0.12500  
..       ...  
894  0.19932  
895  1.00000  
896  0.19932  
897  0.19932  
898  0.08700  

[899 rows x 20 columns]

In [132]:
X_train, X_test, y_train, y_test = train_test_split(df.drop(["target", "smoke"], axis=1), df["target"], stratify=df["target"], test_size=0.1)

In [141]:
from sklearn.model_selection import KFold, cross_val_score
from sklearn.linear_model import LinearRegression, LogisticRegression
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import accuracy_score

lin_model = LinearRegression()
lin_model.fit(X_train, y_train)
lin_scores = cross_val_score(lin_model, X_train, y_train, cv=5)
print("Linear CV and accuracy:")
print(lin_scores)
print(lin_model.score(X_train, y_train))

log_model = LogisticRegression(max_iter=2000)
log_model.fit(X_train, y_train)
log_scores = cross_val_score(log_model, X_train, y_train, cv=5)
print("\nLogistic CV and accuracy:")
print(log_scores)
print(log_model.score(X_train, y_train))

knn_model = KNeighborsClassifier(n_neighbors=15) # played with this number, settled on 15
knn_model.fit(X_train, y_train)
knn_y_pred = knn_model.predict(X_test)
knn_scores = cross_val_score(knn_model, X_train, y_train, cv=5)
print("\nKNN CV and accuracy:")
print(knn_scores)
print(accuracy_score(y_test, knn_y_pred))

print("Logistic regression performed the best.")

Linear CV and accuracy:
[0.45408804 0.38711907 0.34660319 0.57199746 0.29997448]
0.4421630779582859

Logistic CV and accuracy:
[0.80246914 0.77777778 0.81481481 0.85802469 0.76397516]
0.8121137206427689

KNN CV and accuracy:
[0.69135802 0.62345679 0.69753086 0.74074074 0.70807453]
0.6555555555555556
Logistic regression performed the best.
